### ISSUE TITLE
May I use your ukraine.png image on my GitHub profile?

### ISSUE THREAD

**Issue by Shpota** [Tyrrrz/Tyrrrz#1]
I would like to ask for a permission to use the ukraine.png image from this repository on my GitHub profile.

**Comment by Tyrrrz** [comment]
Sure, you're welcome to.

**Comment by Shpota** [comment]
Thank you! May I also ask for a permission to copy the text of your Terms of Use section as well as the majority of your [FAQ section](https://github.com/Tyrrrz/.github/blob/master/docs/why-so-political.md)? I cannot frame it in a better way.

**Comment by Tyrrrz** [comment]
Of course
